### ISSUE TITLE
ChipID evaluation error on CoRdVersionResponseOk class

### ISSUE THREAD

**Issue by andreacioni** [aleon-GmbH/aleoncean#3]
Hi,
playing on this wonderful library I've seen, probably, an error that gives me a wrong chip id when calling getChipId() from CoRdVersionResponseOk class, my real ID is 8E:36:91:45 but it gives me 01:8E:36:91.

Hope this will help you.

Thanks for your good work, very helpful! 

Edit: creating object from : fromResponsePacket(r) 
where r is CommonCommandPacket c = new CommonCommandPacket(CommonCommandCode.CO_RD_VERSION);
r = usb.write(c);

**Comment by maggu2810** [comment]
Thank you for the report.
If you are right, the data is shifted by one byte.
Could you check all members of the CoRdVersionResponseOk object please?

**Comment by andreacioni** [comment]
Ops, sorry but the error was mine, I've calculated the wrong chip id!
