### ISSUE TITLE
New devices for the Eltako FUD61NPN dimmer

### ISSUE THREAD

**Issue by mccare** [aleon-GmbH/aleoncean#6]
Hi,

I've refactored some code to support a local and remote device for the 4BS dimming A53808 CMD2. The Eltako dimmer I use only supports a small subset of definition, so I opted to create two new devices specifically for the FUD61NPN. 

If you like, you can have a look at the code changes here:
https://github.com/aleon-GmbH/aleoncean/compare/master...mccare:eltako-dimmer-support

and maybe give some input if it can be pulled into the master trunk. I would then create a pull request. 

I am kind of uncomfortable with all the changes since the library doesn't contain any tests and my know how is not good enough to start a test suite.

Christian

**Comment by maggu2810** [comment]
Sorry sorry, I have forget your issue completely.
I have implemented it myself for a few days.

You can have a look at if you like.
Perhaps I should also the code that is part of the local and remote device to a parent class.

The next time, don't hesitate to create a PR.

If there still something missing on my code, what do you think.
